apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "jiraservicedesk.stakater.com/v1alpha1",
          "kind": "Project",
          "metadata": {
            "name": "stakater"
          },
          "spec": {
            "assigneeType": "PROJECT_LEAD",
            "description": "Sample project for jira-service-desk-operator",
            "key": "STK",
            "leadAccountId": "5ebfbc3ead226b0ba46c3590",
            "name": "stakater",
            "projectTemplateKey": "com.atlassian.servicedesk:itil-v2-service-desk-project",
            "projectTypeKey": "service_desk",
            "url": "https://stakater.com"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: jira-service-desk-operator.v0.0.8
  namespace: jira-service-desk-operator-system
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Project is the Schema for the projects API
      displayName: Project
      kind: Project
      name: projects.jiraservicedesk.stakater.com
      version: v1alpha1
  description: Kubernetes operator for Jira Service Desk
  displayName: jira-service-desk-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
        - apiGroups:
          - jiraservicedesk.stakater.com
          resources:
          - projects
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - jiraservicedesk.stakater.com
          resources:
          - projects/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: jira-service-desk-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: CONFIG_SECRET_NAME
                  value: jira-service-desk-config
                image: stakater/jira-service-desk-operator:0.0.8
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - jira
  - service
  - desk
  - operator
  - kubernetes
  - openshift
  links:
  - name: Jira Service Desk Operator
    url: https://jira-service-desk-operator.domain
  maintainers:
  - email: hello@stakater.com
    name: Stakater
  maturity: alpha
  provider:
    name: stakater
    url: https://stakater.com
  version: 0.0.8
  webhookdefinitions:
  - admissionReviewVersions: null
    deploymentName: jira-service-desk-operator-webhook
    failurePolicy: Fail
    generateName: vproject.kb.io
    rules:
    - apiGroups:
      - jiraservicedesk.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - projects
    sideEffects: null
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-jiraservicedesk-stakater-com-v1alpha1-project
  - admissionReviewVersions: null
    deploymentName: jira-service-desk-operator-webhook
    failurePolicy: Fail
    generateName: mproject.kb.io
    rules:
    - apiGroups:
      - jiraservicedesk.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - projects
    sideEffects: null
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-jiraservicedesk-stakater-com-v1alpha1-project
