# permissions for end users to view customers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customer-viewer-role
rules:
- apiGroups:
  - jiraservicedesk.stakater.com
  resources:
  - customers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jiraservicedesk.stakater.com
  resources:
  - customers/status
  verbs:
  - get
