# permissions for end users to edit customers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customer-editor-role
rules:
- apiGroups:
  - jiraservicedesk.stakater.com
  resources:
  - customers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jiraservicedesk.stakater.com
  resources:
  - customers/status
  verbs:
  - get
